language: ruby
rvm:
  - 2.4.1

branches:
  only:
    - gh-pages

sudo: required

before_install:
  - nvm install node
  - ruby -v

install:
  - gem install jekyll
  - gem install amp-jekyll
  - npm install -g firebase-tools

script:
  - jekyll build JEKYLL_ENV=production --config _config.yml,_config_live.yml

before_deploy: "echo 'ready?'"

deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "praxis-window-378"