language: ruby
rvm:
  - 2.4.3

branches:
  only:
    - gh-pages

sudo: required

before_install:
  - nvm install node
  - ruby -v

install:
  - gem install jekyll
  - gem install amp-jekyll
  - npm install -g firebase-tools

script:
  - jekyll build JEKYLL_ENV=production --config _config.yml,_config_live.yml

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --project "praxis-window-378" --non-interactive