author: Priya Ramachandran
author_email: happyfeet@lovelldsouza.com
baseurl: '/happyfeet'
title: Happy Feet! &middot; Travel Stories &amp; Photos by Priya &amp; Lovell
description: Stories, photographs and thoughts from a travelling couple taking walks and mapping their routes, while backpacking around India, and parts of the world.
image: https://c1.staticflickr.com/9/8637/16691603885_fed7873429_h.jpg
environment: development
exclude: ['README.md', 'firebase.json', 'firebase-debug.log', 'helper', 'public', 'workflow.txt', '_plugins']
name: The Happy Feet Website
permalink: /:categories/:title
preloadimage: https://happyfeet.us/assets/img/loading.gif
livesiteurl: https://happyfeet.us

plugins:
  - amp-jekyll
ampdir: amp

# Authors of the website.
lovell:
  name: Lovell D&#x27;souza
  email: lovelldies@gmail.com
  web: //www.lovelldsouza.com
  image: https://c2.staticflickr.com/6/5465/buddyicons/20144186@N04_r.jpg
  fb: https://www.facebook.com/lovelldies
priya:
  name: Priya Ramachandran
  email: priya29ramachandran@gmail.com
  web: https://priyaramachandran.com
  image: https://c2.staticflickr.com/8/7568/29440344254_5752503667_q.jpg
  fb: https://www.facebook.com/yyyaaayyyyyy