author: Priya Ramachandran
author_email: happyfeet@lovelldsouza.com
baseurl: /happyfeet
title: Happy Feet!
description: Stories, photographs and thoughts from a travelling couple taking walks and mapping their routes, while backpacking around India, and parts of the world.
image: https://c1.staticflickr.com/9/8637/16691603885_fed7873429_h.jpg
exclude: ['README.md']
markdown: redcarpet
name: The Happy Feet Website
permalink: /:categories/:title
preloadimage: https://c2.staticflickr.com/2/1534/26331374112_75a1493be3.jpg
livesiteurl: http://happtfeet.us

# Authors of the website.
lovell:
  name: Lovell D&#x27;souza
  email: lovelldies@gmail.com
  web: http://www.lovelldsouza.com
  image: https://c2.staticflickr.com/6/5465/buddyicons/20144186@N04_r.jpg
priya:
  name: Priya Ramachandran
  email: priya29ramachandran@gmail.com
  web: http://priyaramachandran.com
  image: https://c2.staticflickr.com/8/7568/29440344254_5752503667_q.jpg